feat: Duplicate Project
Mitcheljager/workshop.codes pull request #288
Opened 2023-04-13 23:48 UTC by Mitcheljager

This PR adds the ability to duplicate a project, creating an exact copy of the content, but of course as a completely new project. This is done by simply passing the content along when creating a project. 

But you may be looking at this thinking "Gee, that's a lot of changes just for duplicating", and you'd be right. There was too much going on in the ProjectsDropdown so I decided to split it up.
1. First up, all common fetch functions have been moved to `utils/project.js`. This includes creating, updating, and destroying a project, among more things.
2. Next the Create modal was moved to it's own component with it's own logic, rather than being housed directly in the ProjectsDropdown component. The modal is still a little bit weird in that it also uses logic from non svelte components from our standard modal javascript. I will leave that refactor for another day. For now it was about clearing up the ProjectsDropdown component.

## Duplicating
![duplicate-project](https://user-images.githubusercontent.com/12848235/231906174-1dfda2c3-7e8d-4d86-a1a1-ac72d583e4ff.gif)

2023-04-13 23:55 UTC, Mitcheljager commented on app/javascript/src/utils/project.js
> +    uuid: Math.random().toString(16).substring(2, 8),
That's cool, but it poses no security risks here. Thanks though mr codescanning!

2023-04-14 00:16 UTC, CactusPuppy requested changes
Most of my suggestions are for copy that was always there, but which I never got a chance to look at. The actually new features look good to me!

2023-04-14 00:16 UTC, CactusPuppy commented on app/javascript/src/components/editor/Modals/CreateProjectModal.svelte
> +          You are not signed in and this is for demonstration purposes only. This will not be saved.
```suggestion
          You are not signed in and this is for demonstration purposes only. Any changes you make will not be saved.
```

2023-04-14 00:16 UTC, CactusPuppy commented on app/javascript/src/components/editor/ProjectsDropdown.svelte
> +    if (!confirm("This will create a copy of the current project. Please confirm!")) return
```suggestion
    if (!confirm("This will create a copy of the current project. Do you want to continue?")) return
```

2023-04-14 00:58 UTC, CactusPuppy approved these changes
LGTM!

2023-04-14 00:58 UTC, merged