Editor: @for loop custom step size
Mitcheljager/workshop.codes pull request #401
Opened 2024-01-28 21:31 UTC by netux

This PR adds an optional step size to @for loops (instead of the default: `1`), active when using the `in steps of` operator.

### Example
```scss
@for (0 through 4 in steps of 2) {
  For.i;
}
```
Renders:
```
  0;
  2;
  4;
```

2024-01-28 22:03 UTC, Mitcheljager requested changes
Cool! It's a bit overkill since you can just do `For.i * x`, but it's also kinda fun, so why not! I did have a couple of nitpicks though

2024-01-28 22:12 UTC, netux commented on app/javascript/src/lib/OWLanguageLegacy.js
> +  if (stream.match(customOperators)) return "atom"
I think it was just leeching off the `identifier` regex.

2024-01-28 22:20 UTC, netux commented
> It's a bit overkill since you can just do `For.i * x`

Yes, but that means outputting `(whatever value For.i was) * x`, which means more elements in the Workshop. So this should help with (micro-)optimization.

For simple cases I also found you can do a mixin like the one below, though its less readable/more verbose.
```
@mixin map01To(value, ifZero, ifOne) { @if (Mixin.value == 0) { Mixin.ifZero } @else { Mixin.ifOne } }

// This is meant to go through 0 to 2, skipping 1
@for (0 through 1) {
  @include map01To(For.i, 0, 2)
}
```

2024-02-01 15:53 UTC, Mitcheljager approved these changes

2024-02-01 15:53 UTC, merged